### PR TITLE
add support airpods max 2 & fix airpods max

### PR DESCRIPTION
**Pull request by b4shtirk1n**

### CODE REVIEW

**Comment by d4rken** [comment]
Thanks, do you have some test data so we can add some tests?

**Comment by b4shtirk1n** [comment]
> Thanks, do you have some test data so we can add some tests?

AirPods Max 2
Address: 08:FF:44:43:DE:70
Vendor ID: 0x004C
Product ID: 0x201F
Firmware Version: 7A291
Minor Type: Headphones
RSSI: -29
Serial Number: MV5DF9H7JK
Services: 0x980019 < HFP AVRCP A2DP AACP GATT ACL >

AirPods Max
Address: 90:9C:4A:ED:53:03
Vendor ID: 0x004C
Product ID: 0x200A
Firmware Version: 6A326
Minor Type: Headphones
Serial Number: H0YGW17FP3WF

**Comment by b4shtirk1n** [comment]
> I mean a BLE broadcast where we know the headphones state, so we can create something like this:
> 
> https://github.com/d4rken-org/capod/blob/858b86af6a30dbf7a4343219f644bb38571e804c/app-common/src/test/java/eu/darken/capod/pods/core/apple/airpods/AirPodsMaxTest.kt#L14-L33

sorry, how ?)

**Comment by d4rken** [comment]
Does it show the device with some hex numbers in the list as unknown device? The hex numbers are the ble broadcast that we need to decode. Just put those in a new test case and check that the values make sense.

**Comment by b4shtirk1n** [comment]
> Does it show the device with some hex numbers in the list as unknown device? 

the device was detected

**Review by d4rken — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
